export const REQUEST_COFFEE_SHOPS = "REQUEST_COFFEE_SHOPS";
export const REQUEST_COFFEE_SHOPS_SUCCESS = "REQUEST_COFFEE_SHOPS_SUCCESS";
export const REQUEST_COFFEE_SHOPS_FAIL = "REQUEST_COFFEE_SHOPS_FAIL";
export const SAVE_LOCATION = "SAVE_LOCATION";
